### ISSUE TITLE
does not redirect and display any payment option on checkout page

### ISSUE THREAD

**Issue by sagar-magento** [mage2pro/mpay24#2]
yes, now option is displayed on checkout page but, when i checked and click on place order it does nothing !! order has been placed, it not display any payment service option, and not redirect to mPay24 site.
![checkout](https://cloud.githubusercontent.com/assets/28754925/26407576/2e248d74-40b9-11e7-8888-3bd67f2f83a7.png)
![success page 1](https://cloud.githubusercontent.com/assets/28754925/26407575/2e02ba96-40b9-11e7-9a78-56b285bcd00b.png)

**Comment by dmitrii-fediuk** [comment]
It is because the extension is no yet released.
It is stated in the Readme: https://github.com/mage2pro/mpay24/tree/25cc7d91#how-to-buy
